print(f"{'-' * 10} DESAFIO 002 {'-' * 10}")
print(f"{'-' * 33}")
print(f"{'':^32}")
print(f"{'-' * 33}")
caractere = str(input("Me diga algo: "))
print(f"se invertermos, o que voce acaboou de digitar, vai ficar assim o {caractere[::-1]}")