print(f"{'-' * 10} DESAFIO 005 {'-' * 10}")
print(f"{'-' * 33}")
print(f"{'':^32}")
print(f"{'-' * 33}")
caractere = str(input("Me diga uma frase: ")).strip()
print(f"A quantidade de palavras nessa frase é equivalente a {len(caractere.split())}")